
import React from 'react';

export const TRANSLATIONS = {
  ar: {
    title: "دوري الجالية اليمنية في تشنغدو",
    navHome: "الرئيسية",
    navRegister: "تسجيل لاعب",
    navStandings: "الترتيب",
    navAdmin: "لوحة التحكم",
    heroTitle: "مرحباً بكم في دوري YCFL",
    heroSubtitle: "أقوى منافسات كرة القدم للجالية اليمنية في مدينة تشنغدو، الصين.",
    registerNow: "سجل الآن",
    name: "الاسم الكامل",
    phone: "الرقم الصيني",
    wechat: "معرف الويتشات",
    submit: "إرسال الطلب",
    successMsg: "تم إرسال طلبك بنجاح! انتظر موافقة المسؤول.",
    adminPanel: "لوحة تحكم المسؤول",
    adminAuthTitle: "الدخول للمسؤولين فقط",
    passwordLabel: "كلمة المرور",
    loginBtn: "دخول",
    wrongPassword: "كلمة المرور غير صحيحة!",
    pendingRequests: "طلبات التسجيل",
    approve: "موافقة",
    reject: "رفض",
    teams: "إدارة الفرق",
    standings: "جدول الترتيب",
    gallery: "معرض الصور",
    uploadPhoto: "إضافة صورة للملعب",
    stats: {
      PAC: "السرعة",
      SHO: "التسديد",
      PAS: "التمرير",
      DRI: "المراوغة",
      DEF: "الدفاع",
      PHY: "القوة",
    }
  },
  zh: {
    title: "成都也门社区足球联赛",
    navHome: "首页",
    navRegister: "球员注册",
    navStandings: "积分榜",
    navAdmin: "管理后台",
    heroTitle: "欢迎来到 YCFL 联赛",
    heroSubtitle: "中国成都也门社区最强足球赛事。",
    registerNow: "立即注册",
    name: "全名",
    phone: "中国手机号",
    wechat: "微信 ID",
    submit: "提交申请",
    successMsg: "申请已提交！请等待管理员审核。",
    adminPanel: "管理员面板",
    adminAuthTitle: "管理员登录",
    passwordLabel: "密码",
    loginBtn: "登录",
    wrongPassword: "密码错误！",
    pendingRequests: "注册审核",
    approve: "批准",
    reject: "拒绝",
    teams: "球队管理",
    standings: "联赛积分榜",
    gallery: "相册管理",
    uploadPhoto: "上传赛场照片",
    stats: {
      PAC: "速度",
      SHO: "射门",
      PAS: "传球",
      DRI: "盘带",
      DEF: "防守",
      PHY: "体能",
    }
  }
};

export const INITIAL_TEAMS = [
  { id: 't1', nameAr: 'صقور سبأ', nameZh: '萨巴雄鹰', players: [], points: 0, played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0 },
  { id: 't2', nameAr: 'نصر تشنغدو', nameZh: '成都胜利', players: [], points: 0, played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0 },
  { id: 't3', nameAr: 'شباب اليمن', nameZh: '也门青年', players: [], points: 0, played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0 },
  { id: 't4', nameAr: 'اتحاد تشنغدو', nameZh: '成都联队', players: [], points: 0, played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0 },
  { id: 't5', nameAr: 'نجوم الجنوب', nameZh: '南方之星', players: [], points: 0, played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0 },
  { id: 't6', nameAr: 'حمير الملكي', nameZh: '皇家希木叶尔', players: [], points: 0, played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0 },
];
